<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>FF14Toolkit.App</RootNamespace>
    <AssemblyName>FF14Toolkit.App</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NeutralLanguage>ja-JP</NeutralLanguage>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="Assets\Templates\Crafting\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Templates\Crafting\*.ppm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lumina" Version="7.5.0" />
    <PackageReference Include="Lumina.Excel" Version="7.4.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <Target Name="CopyCraftTemplates" AfterTargets="Build">
    <MakeDir Directories="$(OutDir)Assets\Templates\Crafting" />
    <Copy SourceFiles="Assets\Templates\Crafting\craft-start-button.ppm;Assets\Templates\Crafting\craft-window-anchor.ppm;Assets\Templates\Crafting\crafting-log-title.ppm;Assets\Templates\Crafting\crafting-log-title.json"
          DestinationFolder="$(OutDir)Assets\Templates\Crafting"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
